[[language]]
name = "python"
scope = "source.python"
file-types = ["py"]
auto-format = true
formatter = {command = "black", args = ["-q", "-"]}
language-servers = [ "pyright" ]
indent = { tab-width = 4, unit = "    " }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[[language]]
name = "go"
scope = "source.go"
file-types = ["go"]
auto-format = true

[language-server.go]
command = "gopls"
args = []

[[language]]
name = "html"
scope = "text.html.basic"
file-types = ["html"]
auto-format = true

[language-server.html]
command = "vscode-html-language-server"
args = ["--stdio"]

[[language]]
name = "css"
scope = "source.css"
file-types = ["css"]
auto-format = true

[language-server.css]
command = "vscode-css-language-server"
args = ["--stdio"]

[[language]]
name = "terraform"
scope = "source.terraform"
file-types = ["tf"]
auto-format = true

[language-server.terraform]
command = "terraform-ls"
args = ["serve"]

[[language]]
name = "kubernetes"
scope = "source.yaml"
file-types = ["yaml", "yml"]
auto-format = true

[language-server.kubernetes]
command = "yaml-language-server"
args = ["--stdio"]

[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "javascript"
file-types = ["js"]
auto-format = true

[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "typescript"
file-types = ["ts", "tsx"]
auto-format = true

[language-server.typescript]
command = "typescript-language-server"
args = ["--stdio"]

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
auto-format = true
roots = [
    "Cargo.toml",
    "Cargo.lock"
]

[language-server.rust-anaylzer]
command = "rust-analyzer"
args = []

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
